import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import  Feed  from './Feed'
import  SideBar  from './SideBar'
import { Widgets } from './Widgets'

export default function Home({res}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex min-h-screen mx-auto bg-slate-100'>
      {/* SideBar */}
      <SideBar/>
      {/* Feed */}
      <Feed/>
      {/* widgets */}
      <Widgets res={res.articles}/>
      </main>
    </div>
  )
}
//https://saurav.tech/NewsAPI/top-headlines/category/business/in.json
export async function getServerSideProps(){
  const res=await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/in.json").then((res)=>res.json())
  return{
    props:{
      res,
    }
  }
}